SHELL := /bin/bash
.DEFAULT_GOAL := build

build:
	@gcc fifoget.c -o fifoget
	@gcc fifoskp.c -o fifoskp
	@gcc fifoply.c -o fifoply
	@gcc fiforev.c -o fiforev

fifoget:
	clear;
	@gcc fifoget.c -o fifoget

fifoskp:
	clear;
	@gcc fifoskp.c -o fifoskp

fifoply:
	clear;
	@gcc fifoply.c -o fifoply

fiforev:
	clear;
	@gcc fiforev.c -o fiforev